url: https://agbero.dev
frame_class: "frame mw6 pa2 h-100"
defaults:
  - scope:
      path: "assets/img"
    values:
      image: true
  - scope:
      path: "assets/papers"
    values:
      pdf: true
